apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-test
  namespace: infra
spec:
  generators:
  - git:
      repoURL: https://github.com/pedominguezbr/argocd-example.git
      revision: HEAD
      files:
      - path: "helm-values-files-omnitok/**/*.yaml"
  template:
    metadata:
      name: '{{ omnitok.deploymentName }}'
    spec:
      destination:
        namespace: "{{ omnitok.namespace }}"
        server: https://kubernetes.default.svc
      project: "{{ omnitok.namespace }}"
      source:
        path: "./"
        repoURL: https://github.com/pedominguezbr/argocd-example.git
        targetRevision: HEAD
        plugin:
          name: helm-omnitok-a
          env:
            - name: HELM_RELEASE_NAME
              value: "{{ omnitok.deploymentName }}"
            - name: HELM_CHART_VERSION
              value: "{{ omnitok.chartVersion }}"
            - name: NAMESPACE
              value: "{{omnitok.namespace}}"
            - name: HELM_REPO_URL
              value: "{{ omnitok.chartPath }}"
            - name: HELM_CHART_NAME
              value: "{{ omnitok.chartName }}"
            - name: HELM_VALUES_FILE
              value: "{{ path }}/{{ path.filename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
