apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-test-a
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/pedominguezbr/argocd-example.git
      revision: HEAD
      files:
      - path: "helm-values-files/**/*.yaml"
  template:
    metadata:
      name: '{{ yotpo.deploymentName }}'
    spec:
      destination:
        namespace: "{{ yotpo.namespace }}"
        server: https://kubernetes.default.svc
      project: infra
      source:
        path: "./"
        repoURL: https://github.com/pedominguezbr/argocd-example.git
        targetRevision: HEAD
        plugin:
          name: helm-omnitok-a
          env:
            - name: HELM_RELEASE_NAME
              value: "{{ yotpo.deploymentName }}"
            - name: HELM_CHART_VERSION
              value: "{{ yotpo.chartVersion }}"
            - name: NAMESPACE
              value: "{{yotpo.namespace}}"
            - name: HELM_REPO_URL
              value: "{{ yotpo.chartPath }}"
            - name: HELM_CHART_NAME
              value: "{{ yotpo.chartName }}"
            - name: HELM_VALUES_FILE
              value: "{{ path }}/{{ path.filename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true